source 'http://rubygems.org'

# Test suite
gem 'cucumber'
gem 'rspec'
gem 'page-object'
gem 'viewcumber'
gem 'rails'

# Data and dependencies
gem 'activerecord', '3.2.12'
gem 'activerecord-mysql2-adapter'
gem 'factory_girl'
gem 'database_cleaner'
gem 'faker'
#gem 'sqlite3'

gem 'pry'
